apiVersion: v1
kind: Secret
metadata:
  name: inknos-issuematch-dev-secrets
stringData:
  session_secret: 31ad178868c8e1aeb65f085ab536c7e6d6db6544f48c3d92c4e876fcebd621ea
  admin_username: admin
  admin_password: password
